plugins {
    id 'java'
}

group = 'com.teamsolution.notification'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':common:common-core-grpc-client')
    implementation project(':common:common-core-kafka')
    implementation project(':common:common-core-jpa')

    // Eureka Client
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    // WebSocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    // Email
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // Flyway
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    // MapStruct processor
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    runtimeOnly 'org.postgresql:postgresql'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

test {
    useJUnitPlatform()
}